---
title: "All past talks"
author: "Frida Gomam"
date: 2015-07-23T21:13:14-05:00
categories: ["R"]
tags: ["R Markdown", "plot", "regression"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Paper resentations:

Langton, S. & **Adepeju, M.** **2018**. A longitudinal study of offender residential concentration in the UK. Presented at the European Society of Criminology - Sarajevo, Bosnia and Herzegovina - 29th August 2018.

**Adepeju, M.** **2017** Developing a hybrid hotspot approach for improving the accuracy of crime prediction. ECTQG 18th European Colloquium on Theoretical and Quantitative Geography, York, United Kingdom, September 2017	

**Adepeju, M.** & Cheng, T. **2016** A Spatially-Integrated Sparse Point Time Series (SSPT) Prediction Method. The 26th Annual Conference of the International Environmetrics Society, Edinburgh, Scotland, UK July, 2016 

**Adepeju, M.**, Rosser, G., & Cheng T. **2015** Comparative analysis of predictive hotspot methods. Association of American Geographers, Annual Meeting. Chicago, IL, USA, April 2015 

**Adepeju, M.** & Cheng, T. **2014** Prospective Space-Time Scan Statistics (STSS) for Crime Prediction. 22nd Annual Popfest conference, London, UK, August 2014.  

**Adepeju, M.**, Cheng, T., & Nakaya, T. **2014** Crime pattern detection for predictive policing. Association of American Geographers, Annual Meeting. Tampa, FL, USA, April 2013 

Cheng, T. & **Adepeju, M.** **2013** Implications of the difference between the Prospective and Retrospective Space-time scan statistics. ECTQG 18th European Colloquium on Theoretical and Quantitative Geography, Dourdan, France, September 2013.
